### ISSUE TITLE
播放器回调信息少

### ISSUE THREAD

**Issue by microzhang715** [waterfoxfox/RtmpPlayer-Android#2]
请问能否增加标准的MediaPlayer播放器接口回调消息给java层，这样的设计会更加通用。
rtmp的追帧效果很给力，大赞一个

能否构建一个交流群，后续进一步做技术探讨

**Comment by waterfoxfox** [comment]
没有了解过标准的MediaPlayer接口相关，可以加我QQ 1821554146 ，谢谢
